
templates:
  #===========================================================================
  rodosTest_map: !template
  #===========================================================================
    reportTemplate: rodosTest_map.jrxml
    attributes:
      map: &map !map
        maxDpi: 400
        width: 520
        height: 536
      northArrow: &northArrow !northArrow
        size: 45
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(0, 0, 0, 0)"
      scalebar: &scalebar !scalebar
        width: 159
        height: 36
        default:
          backgroundColor: "rgba(200, 200, 200, 100)"
          align: "right"
          intervals: 2
          fontSize: 10
          renderAsSvg: true
      map_attribution: &map_attribution !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}

  #===========================================================================
  rodosTest: !template
  #===========================================================================
    reportTemplate: rodosTest.jrxml
    attributes:
      map_template: !string
        default: "rodosTest_map.jasper"
      map: *map
      northArrow: *northArrow
      scalebar: *scalebar
      map_attribution: *map_attribution

      is_exercise: !string
        default: "false"
      title: !string {}

      legend: !legend {}

      description: !string
        default: ""
      comment: !string
        default: ""
      impressum: !string {}

      doc_creator: !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}
    - !prepareLegend
      template: legend.jrxml
