
# enthält 3 Templates + Template für die Summary
templates: 
  #===========================================================================
  # template for map only
  imis_A4_map: !template
    reportTemplate: imis_A4_map.jrxml
    attributes:
      map: &map !map
        # DPI Vorschläge für Aufklappbox
        dpiSuggestions: [90, 72, 150, 200, 300]
        maxDpi: 400
        # Breite/Höhe der Map (entspricht Ausmaßen des Sub-Reports)
        width: 518
        height: 534
      northArrow: &northArrow !northArrow
        # Grafik entspricht einem Quadrat mit gleicher Breite/Höhe
        size: 45
        default:
          # Dateipfad in Verzeichnis
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(255, 255, 255, 200)"
      scalebar: &scalebar !scalebar
        width: 159
        height: 22
        default:
          backgroundColor: "rgba(255, 255, 255, 200)"
          align: "right"
          # Anzahl der schwarz/weiß-Abschnitte (mind. 2; default 3)
          intervals: 2
          fontSize: 10
          renderAsSvg: true
          # geodätische Messung
          geodetic: true
      map_attribution: &map_attribution !string
        default: "<div>&copy;Bundesamt f&uuml;r Strahlenschutz</div>"

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    # Prozessors, die die atrributes bedienen
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}
    - !configureHttpRequests
      httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"   

  #===========================================================================
  # template for legend only
  imis_A4_legend: !template
    reportTemplate: imis_A4_legend.jrxml
    attributes:
      is_exercise: &is_exercise !boolean
        default: true
      title: &title !string
        default: "<div><b>KOALA Druckdienst</b></div>"

      legend: &legend !legend {}

      description: &description !string
        default: "<div><b>Datenquelle: IMIS</b><br>&lt;...BITTE EINTRAGEN...&gt;</div>"
      comment: &comment !string
        default: "<div>&lt;..Kommentar: ...&gt; </div>"
      impressum: &impressum !string
        default: "<div><b>&copy;Bundesamt f&uuml;r Strahlenschutz<br>(im Auftrag des BMU)</b><br></div>"
        
    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !prepareLegend
      template: legend.jrxml
    - !configureHttpRequests
      httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"   

  #===========================================================================

              
  #===========================================================================
  # template for document including map and legend
  imis_A4: !template
    reportTemplate: imis_A4.jrxml
    attributes:
      map_template: !string
        default: "imis_A4_map.jasper"
      map: *map
      northArrow: *northArrow
      scalebar: *scalebar
      map_attribution: *map_attribution

      legend_template: !string
        default: "imis_A4_legend.jasper"
      is_exercise: *is_exercise
      title: *title
      legend: *legend
      description: *description
      comment: *comment
      impressum: *impressum
      layerdata: !datasource
        attributes:
          title: !string
            default: ""
          table: !table {} 
      doc_creator: !string {}

    processors:
    # compile all reports in current directory
    - !reportBuilder 
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}
    - !prepareLegend
      template: legend.jrxml
    - !createDataSource
      inputMapper: {layerdata: datasource}
      outputMapper: {jrDataSource: layerdata2}
      processors:
      - !reportBuilder
        directory: '.'
      - !prepareTable
        columns: {}
        dynamic: true
        jasperTemplate: results_landscape_2.jrxml
        firstDetailStyle: column_style_1
        detailStyle: column_style_2
        lastDetailStyle: column_style_3
        firstHeaderStyle: header_style_1
        headerStyle: header_style_2
        lastHeaderStyle: header_style_3
        excludeColumns: ["owner, readonly, id"]
        # adjust the table report width to the landscape format
        reportWidth: 800
        inputMapper: {table: table}
        outputMapper: {tableDataSource: table2}
      - !reportBuilder
        directory: '.'  
    - !configureHttpRequests
      httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"            
