
templates:
  #===========================================================================
  # template for map only
  imis_A3_map: !template
    reportTemplate: imis_A3_map.jrxml
    attributes:
      map: &map !map
        # DPI Vorschläge für Aufklappbox
        dpiSuggestions: [90, 72, 150, 200, 300]
        maxDpi: 400
        # Breite/Höhe der Map (entspricht Ausmaßen des Sub-Reports)
        width: 848
        height: 778
      northArrow: &northArrow !northArrow
        size: 45
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(255, 255, 255, 200)"
      scalebar: &scalebar !scalebar
        width: 159
        height: 22
        default:
          backgroundColor: "rgba(255, 255, 255, 200)"
          align: "right"
          intervals: 2
          fontSize: 10
          renderAsSvg: true
          geodetic: true
      map_attribution: &map_attribution !string
        default: "<div>&copy;Bundesamt f&uuml;r Strahlenschutz</div>"

    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !createMap {}
      - !createNorthArrow {}
      - !createScalebar {}
      - !configureHttpRequests
        httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"
              #https://www.imis.bfs.de/ogc/inspire/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/inspire/$1"
              #https://www.imis.bfs.de/ogc/opendata/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/opendata/$1"
              #https://www.imis.bfs.de/ogc/geozg/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/geozg/$1"
              #https://www.imis.bfs.de/ogc/bfs/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/bfs/$1"
              #https://www.imis.bfs.de/ogc/imis/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/imis/$1"
              #https://www.imis.bfs.de/ogc/rodos/wms(.*) : "http://jroapp-muc.rodos.bfs.de:8080/geoserver/jrodos_res/ows$1"
              #https://www.imis.bfs.de/ogc/osm/wms(.*) : "http://osm-muc.bfs.de/osm/wms_osm$1"
              #https://www.imis.bfs.de/ogc/tiles/(.*) : "http://osm-muc.bfs.de/mapcache/$1"

  #===========================================================================
  # template for legend only
  imis_A3_legend: !template
    reportTemplate: imis_A3_legend.jrxml
    attributes:
      is_exercise: &is_exercise !boolean
        default: true
      title: &title !string
        default: "<div><b>KOALA Druckdienst</b></div>"

      legend: &legend !legend {}

      description: &description !string
        default: "<div><b>Datenquelle: IMIS</b><br>&lt;...BITTE EINTRAGEN...&gt;</div>"
      comment: &comment !string
        default: "<div>&lt;... Kommentar: ...&gt; </div>"
      impressum: &impressum !string
        default: "<div><b>&copy;Bundesamt f&uuml;r Strahlenschutz<br>(im Auftrag des BMU)</b><br></div>"

    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !prepareLegend
        template: legend.jrxml
      - !configureHttpRequests
        httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"
              #https://www.imis.bfs.de/ogc/inspire/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/inspire/$1"
              #https://www.imis.bfs.de/ogc/opendata/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/opendata/$1"
              #https://www.imis.bfs.de/ogc/geozg/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/geozg/$1"
              #https://www.imis.bfs.de/ogc/bfs/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/bfs/$1"
              #https://www.imis.bfs.de/ogc/imis/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/imis/$1"
              #https://www.imis.bfs.de/ogc/rodos/wms(.*) : "http://jroapp-muc.rodos.bfs.de:8080/geoserver/jrodos_res/ows$1"
              #https://www.imis.bfs.de/ogc/osm/wms(.*) : "http://osm-muc.bfs.de/osm/wms_osm$1"
              #https://www.imis.bfs.de/ogc/tiles/(.*) : "http://osm-muc.bfs.de/mapcache/$1"  

  #===========================================================================
  # template for document including map and legend
  imis_A3: !template
    reportTemplate: imis_A3.jrxml
    attributes:
      map_template: !string
        default: "imis_A3_map.jasper"
      map: *map
      northArrow: *northArrow
      scalebar: *scalebar
      map_attribution: *map_attribution

      legend_template: !string
        default: "imis_A3_legend.jasper"
      is_exercise: *is_exercise
      title: *title
      legend: *legend
      description: *description
      comment: *comment
      impressum: *impressum

      doc_creator: !string {}

    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !createMap {}
      - !createNorthArrow {}
      - !createScalebar {}
      - !prepareLegend
        template: legend.jrxml
      - !configureHttpRequests
        httpProcessors:
          - !mapUri
            mapping:
              https://entw-imis.lab.bfs.de/(.*) : "http://test-docker-fr.lab.bfs.de/$1"
              https://www.imis.bfs.de/ogc/tiles/wms?(.*) : "http://test-osm01-muc.lab.bfs.de/osm/wms_osm?$1"
              #https://www.imis.bfs.de/ogc/inspire/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/inspire/$1"
              #https://www.imis.bfs.de/ogc/opendata/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/opendata/$1"
              #https://www.imis.bfs.de/ogc/geozg/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/geozg/$1"
              #https://www.imis.bfs.de/ogc/bfs/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/bfs/$1"
              #https://www.imis.bfs.de/ogc/imis/(.*) : "http://ogc-muc.bfs.de:8080/geoserver/imis/$1"
              #https://www.imis.bfs.de/ogc/rodos/wms(.*) : "http://jroapp-muc.rodos.bfs.de:8080/geoserver/jrodos_res/ows$1"
              #https://www.imis.bfs.de/ogc/osm/wms(.*) : "http://osm-muc.bfs.de/osm/wms_osm$1"
              #https://www.imis.bfs.de/ogc/tiles/(.*) : "http://osm-muc.bfs.de/mapcache/$1"  
