
templates:
  #===========================================================================
  # template for map only
  Test_map: !template
    reportTemplate: Test_map.jrxml
    attributes:
      map: &map !map
        maxDpi: 400
        width: 520
        height: 536
      northArrow: &northArrow !northArrow
        size: 45
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(0, 0, 0, 0)"
      scalebar: &scalebar !scalebar
        width: 159
        height: 22
        default:
          backgroundColor: "rgba(200, 200, 200, 100)"
          align: "right"
          intervals: 2
          fontSize: 10
          renderAsSvg: true
          geodetic: true
      map_attribution: &map_attribution !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}

  #===========================================================================
  # template for legend only
  Test_legend: !template
    reportTemplate: Test_legend.jrxml
    attributes:
      is_exercise: &is_exercise !string
        default: "true"
      title: &title !string {}

      legend: &legend !legend {}

      description: &description !string
        default: ""
      comment: &comment !string
        default: ""
      impressum: &impressum !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !prepareLegend
      template: legend.jrxml

  #===========================================================================
  # template for document including map and legend
  Test: !template
    reportTemplate: Test.jrxml
    attributes:
      map_template: !string
        default: "Test_map.jasper"
      map: *map
      northArrow: *northArrow
      scalebar: *scalebar
      map_attribution: *map_attribution

      legend_template: !string
        default: "Test_legend.jasper"
      is_exercise: *is_exercise
      title: *title
      legend: *legend
      description: *description
      comment: *comment
      impressum: *impressum

      doc_creator: !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}
    - !prepareLegend
      template: legend.jrxml
