throwErrorOnExtraParameters: false

templates:
  A4 landscape: !template
    reportTemplate: rei_quartal_mantel.jrxml
    attributes:
      doc_creator: !string {}  
      #rei_quartal_template: !string
      #  default: "rei_quartal.jasper"
      #rei_quartal_table_template: !string
      #  default: "rei_quartal_table.jasper"
      proben: !datasource
        attributes:
          messRegime: !string
            default: ""
          netzId: !string
            default: ""  
          netzbetreiber: !string
            default: ""            
          anlagebeschr: !string
            default: ""
          anlage: !string
            default: ""
          medium: !string
            default: ""
          qmitteSammelzeitraum: !string
            default: 0
          jmitteSammelzeitraum: !string
            default: 0
          mitteSammelzeitraum: !string
            default: 0 
          dBasis: !string
            default: ""
          hpNr: !string
            default: ""
          npNr: !string
            default: ""
          mstLaborId: !string
            default: ""
          mstLabor: !string
            default: ""
          umw: !string
            default: ""
          umwID: !string
            default: ""  
          # Achtung: gg
          reiproggrp: !string
            default: ""  
          # Achtung: gg
          reiproggrpbeschr: !string
            default: ""
          # mmt=Messmethode
          mmt: !string
            default: ""
          mmtID: !string
            default: ""  
          prnId: !string
            default: ""  
          prnBezeichnung: !string
            default: ""
          prnKurzBezeichnung: !string
            default: ""  
          mpl: !string
            default: ""
          mplCode: !string
            default: ""  
          probenart: !string
            default: ""
          externeProbeId: !string
            default: ""
          letzteAenderung: !string
            default: 0
          media: !string
            default: ""
          mediaDesk: !string
            default: ""
          messungen: !datasource
            attributes:
              messbeginn: !string
                default: 0            
              peBegin: !string
                default: 0
              peEnd: !string
                default: 0
              # Messpunkt
              ortKurztext: !string
                default: ""
              ortLangtext: !string
                default: ""
              ortId: !string
                default: ""  
              eGem: !string
                default: "" 
              eGemId: !string
                default: ""                 
              berichtstext: !string
                default: ""               
              messgroesse: !string
                default: ""
              bemerkungen: !string
                default: "" 
              einheit: !string
                default: ""   
              # Messwert
              wert: !string
                default: ""
              # relative Messunsicherheit
              fehler: !string
                default: ""
              nwg: !string
                default: ""
              nwgZuMesswert: !string
                default: ""
              messdauer: !string
                default: 0
              pKommentar: !string
                default: ""               
              mKommentar: !string
                default: ""               
              pzs: !string
                default: ""
              #table: !table {}  

    processors:
    - !reportBuilder
      directory: '.'
    - !createDataSource
      inputMapper: {proben: datasource}
      outputMapper: {jrDataSource: proben2}
      processors:
      - !createDataSource
        inputMapper: {messungen: datasource}
        outputMapper: {jrDataSource: messungen2}
        #processors:
      #- !prepareTable
        #  columns: {}
      #dynamic: true
        #  inputMapper: {table: table}
        #  outputMapper: {tableDataSource: table2}  
        processors:
        - !reportBuilder
          directory: '.'
#    - !prepareTable
#      columns: {}
#      dynamic: true
#      jasperTemplate: table.jrxml
#      firstDetailStyle: column_style_1
#      detailStyle: column_style_2
#      lastDetailStyle: column_style_3
#      firstHeaderStyle: header_style_1
#      headerStyle: header_style_2
#      lastHeaderStyle: header_style_3
#      excludeColumns: ["owner, readonly, id"]
#      inputMapper: {table: table}
#      #vor Änderung: outputMapper: {table: table}
#      #table2 da mit table nicht doppelt für Input und Output verwendet werden darf (ab V3.9 können Attribute nicht überschrieben werden), ebenfalls ab V3.9 tableDataSource 
#      outputMapper: {tableDataSource: table2} 
#      processors:   
#      - !reportBuilder
#        directory: '.'  
