
templates:
  #===========================================================================
  # template for map only
  imis_A4_map: !template
    reportTemplate: imis_A4_map.jrxml
    attributes:
      map: &map !map
        maxDpi: 400
        width: 518
        height: 534
      northArrow: &northArrow !northArrow
        size: 45
        default:
          graphic: "file://NorthArrow_10.svg"
          backgroundColor: "rgba(255, 255, 255, 200)"
      scalebar: &scalebar !scalebar
        width: 159
        height: 22
        default:
          backgroundColor: "rgba(255, 255, 255, 200)"
          align: "right"
          intervals: 2
          fontSize: 10
          renderAsSvg: true
      map_attribution: &map_attribution !string
        default: "<div>&copy;Bundesamt f&uuml;r Strahlenschutz</div>"

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}

  #===========================================================================
  # template for legend only
  imis_A4_legend: !template
    reportTemplate: imis_A4_legend.jrxml
    attributes:
      is_exercise: &is_exercise !string
        default: "true"
      title: &title !string
        default: "<div><b>KOALA Druckdienst</b></div>"

      legend: &legend !legend {}

      description: &description !string
        default: "<div><b>Datenquelle: RODOS</b><br>Freisetzungsort: &lt;...BITTE EINTRAGEN...&gt;<br>Ereignis: &lt;...BITTE EINTRAGEN...&gt;</div>"
      comment: &comment !string
        default: "<div>&lt;..Kommentar: ...&gt; </div>"
      impressum: &impressum !string
        default: "<div><b>&copy;Bundesamt f&uuml;r Strahlenschutz<br>(im Auftrag des BMUB)</b><br><br>RODOS-Zentrale<br>Rechnung vom: &lt;...BITTE EINTRAGEN...&gt;<br>RODOS-Zentrale<br>Lauf Kennung: &lt;...BITTE EINTRAGEN...&gt;<br></div>"

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !prepareLegend
      template: legend.jrxml

  #===========================================================================
  # template for document including map and legend
  imis_A4: !template
    reportTemplate: imis_A4.jrxml
    attributes:
      map_template: !string
        default: "imis_A4_map.jasper"
      map: *map
      northArrow: *northArrow
      scalebar: *scalebar
      map_attribution: *map_attribution

      legend_template: !string
        default: "imis_A4_legend.jasper"
      is_exercise: *is_exercise
      title: *title
      legend: *legend
      description: *description
      comment: *comment
      impressum: *impressum

      doc_creator: !string {}

    processors:
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createNorthArrow {}
    - !createScalebar {}
    - !prepareLegend
      template: legend.jrxml
