
throwErrorOnExtraParameters: false
#===========================================================================
# Template for full Erfassungsbogen

templates:
  A4 portrait: !template
    reportTemplate: erfassungsbogen_mantel.jrxml
    attributes:
      proben: !datasource
        attributes:
          id: !string
            default: ""
          baId: !string
            default: ""
          datenbasis: !string
            default: ""
          deskriptoren: !datasource
            attributes:
              S0: !string
                default: ""
              S1: !string
                default: ""
              S2: !string
                default: ""
              S3: !string
                default: ""
              S4: !string
                default: ""
              S5: !string
                default: ""
              S6: !string
                default: ""
              S7: !string
                default: ""
              S8: !string
                default: ""
              S9: !string
                default: ""
              S10: !string
                default: ""
              S11: !string
                default: ""
          erzeugerId: !string
            default: ""
          hauptprobenNr: !string
            default: ""
          umw: !string
            default: ""
          mpl: !string
            default: ""
          probenart: !string
            default: ""
          messstelle.messStelle: !string
            default: ""
          idAlt: !string
            default: ""
          labormessstelle.messStelle: !string
            default: ""
          letzteAenderung: !string
            default: 0
          media: !string
            default: ""
          mediaDesk: !string
            default: ""
          messstelle: !datasource
            attributes:
              beschreibung: !string
                default: ""
          ortszuordnung: !datasource
            attributes:
              ortszuordnungTyp: !string
                default: ""
              ort.staat: !string
                default: ""
              ort.koordXExtern: !string
                default: ""
              ort.koordYExtern: !string
                default: ""
              ort.kdaId: !string
                default: ""
              ort.gemId: !string
                default: ""
              ort.gem: !string
                default: ""
          probeentnahmeBeginn: !string
            default: 0
          probeentnahmeEnde: !string
            default: 0
          solldatumBeginn: !string
            default: 0
          solldatumEnde: !string
            default: 0
          zusatzwerte: !datasource
            attributes:
              messwertPzs: !string
                default: ""
              messfehler: !string
                default: ""
              nwgZuMesswert: !string
                default: ""
              messwertNwg: !string
                default: "TODO"
              meh: !string
                default: "TODO"
              pzsId: !string
                default: ""
          kommentare: !datasource
            attributes:
              datum: !string
                default: ""
              mst: !string
                default: ""
              text: !string
                default: ""
              id: !integer
                default: 0
          messungen: !datasource
            attributes:
              fertig: !string
                default: ""
              geplant: !string
                default: ""
              idAlt: !string
                default: ""
              letzteAenderung: !string
                default: ""
              messdauer: !string
                default: ""
              messzeitpunkt: !string
                default: ""
              mmt: !string
                default: ""
              nebenprobenNr: !string
                default: ""
              probeId: !string
                default: ""
              status: !string
                default: ""
              statusprotokoll: !datasource
                attributes:
                  datum: !string
                    default: ""
                  mst: !string
                    default: ""
                  statusStufe: !string
                    default: ""
                  statusWert: !string
                    default: ""
                  text: !string
                    default: ""
              kommentare: !datasource
                attributes:
                  mst: !string
                    default: ""
                  datum: !string
                    default: ""
                  text: !string
                    default: ""
              messwerte: !datasource
                attributes:
                  grenzwertueberschreitung: !string
                    default: ""
                  letzeAenderung: !string
                    default: ""
                  meh: !string
                    default: ""
                  messfehler: !string
                    default: ""
                  messgroesse: !string
                    default: ""
                  messwert: !string
                    default: ""
                  messwertNwg: !string
                    default: ""
                  nwgZuMesswert: !string
                    default: ""


    processors:
    - !reportBuilder
      directory: '.'
    - !createDataSource
      inputMapper: {proben: datasource}
      outputMapper: {jrDataSource: proben2}
      processors:
      - !createDataSource
        inputMapper: {deskriptoren: datasource}
        outputMapper: {jrDataSource: deskriptoren2}
        processors:
        - !reportBuilder
          directory: '.'
      - !createDataSource
        inputMapper: {messstelle: datasource}
        outputMapper: {jrDataSource: messstelle2}
        processors:
        - !reportBuilder
          directory: '.'
      - !createDataSource
        inputMapper: {zusatzwerte: datasource}
        outputMapper: {jrDataSource: zusatzwerte2}
        processors:
        - !reportBuilder
          directory: '.'
      - !createDataSource
        inputMapper: {ortszuordnung: datasource}
        outputMapper: {jrDataSource: ortszuordnung2}
        processors:
        - !reportBuilder
          directory: '.'
      - !createDataSource
        inputMapper: {kommentare: datasource}
        outputMapper: {jrDataSource: kommentare2}
        processors:
        - !reportBuilder
          directory: '.'
      - !createDataSource
        inputMapper: {messungen: datasource}
        outputMapper: {jrDataSource: messungen2}
        processors:
        - !createDataSource
          inputMapper: {kommentare: datasource}
          outputMapper: {jrDataSource: kommentare2}
          processors:
          - !reportBuilder
            directory: '.'
        - !createDataSource
          inputMapper: {statusprotokoll: datasource}
          outputMapper: {jrDataSource: statusprotokoll2}
          processors:
          - !reportBuilder
            directory: '.'
        - !createDataSource
          inputMapper: {messwerte: datasource}
          outputMapper: {jrDataSource: messwerte2}
          processors:
          - !reportBuilder
            directory: '.'    
